spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfg_dev
    username: sfg_dev_user
    password: aidian3k
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: mysql
  sql:
    init:
      platform: mysql
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#             action: create
#              create-target: mysql-generation-schema.sql