spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfg_dev_user
    username: sfg_dev_user
    password: aidian3k
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: mysql
#    properties:
#      javax:
#       persistence:
#          create-source: metadata
#         scripts:
#            action: create
#            create-target: sql_script.sql