spring:
  datasource:
    url: jdbc:mysql//localhost:3306/sfg_prod
    username: sfg_prod_user
    password: aidian3k
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create